// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/smartisa-launch/SmartisaLaunch.tsx": () => import("../components/mockups/smartisa-launch/SmartisaLaunch.tsx")
};
